server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/stocktracker
    redis:
      url: redis://:sa@localhost:6379
  cache:
    redis:
      time-to-live: 60000

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger/index.html

stock:
  client:
    brapi:
      url: https://brapi.dev/api/quote
      token: token

security:
  secretLoginKey: 'a-minha-chave-secreta'