server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      ssl:
        enabled: true
        invalid-hostname-allowed: true
        #ca-file: /etc/mongo/certs/ca.pem
    redis:
      url: ${REDIS_URL}
  cache:
    redis:
      time-to-live: 60000

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger/index.html

stock:
  client:
    brapi:
      active: ${STOCK_CLIENT_BRAPI_ACTIVE}
      url: ${STOCK_CLIENT_BRAPI_URL}
      token: ${STOCK_CLIENT_BRAPI_TOKEN}

security:
  secretLoginKey: ${SECURITY_SECRET_LOGIN_KEY}