server:
  port: 8080

spring:
  data:
    mongodb:
      #uri: mongodb+srv://stocktracking:WDjkWVFKCDw40jrC@paneladev.78l2uxy.mongodb.net/stocktracking
      host: localhost
      port: 27017
      database: stocktracker
    redis:
      host: localhost
      port: 6379
      password: sa
  cache:
    redis:
      time-to-live: 60000

stock:
  client:
    brapi:
      url: https://brapi.dev/api/quote
      token: 5o2DQc1FAK8rq39UbUMxV7